# Generated by Django 3.2.19 on 2023-05-21 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_keys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('ac5e2e5c-3634-4088-83e0-03a1b1e20f56'))),
                ('label', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_keys', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_keys.accesskey')),
            ],
        ),
    ]
