# Generated by Django 3.2.19 on 2023-05-21 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('af052e34-03c1-48b5-9e6e-3c7a7444d091')),
        ),
    ]
