# Generated by Django 3.2.19 on 2023-05-21 13:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0096c394-d35f-4f3f-83b8-b72284c15d7d')),
        ),
    ]
