# Generated by Django 3.2.19 on 2023-05-21 13:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2f6c4492-423f-4b80-a0a7-106a8935289e')),
        ),
    ]
