# Generated by Django 3.2.19 on 2023-05-21 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20230521_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='access_keys',
            new_name='access_key',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('247dff7d-7886-49e4-8ce5-e792ed755bf3')),
        ),
    ]
