# Generated by Django 3.2.19 on 2023-05-21 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20230521_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('566ae6ac-9a33-4392-845e-4f676a7ef837')),
        ),
    ]
