# Generated by Django 3.2.19 on 2023-05-21 13:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_restaurant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3ae2f562-6317-4f27-a84c-234b89875102')),
        ),
    ]
