# Generated by Django 3.2.19 on 2023-05-21 13:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_restaurant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fffad337-f59c-4975-bce0-d219ffde3ec4')),
        ),
    ]
