# Generated by Django 3.2.19 on 2023-05-21 14:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
